### ISSUE TITLE
Enhancement options

### ISSUE THREAD

**Issue by peternewman** [gobo-ws/ola-trigger-crelay-dmx#1]
You could potentially integrate this into the OLA GPIO module:
https://github.com/OpenLightingProject/ola/tree/master/plugins/gpio

You should probably also open a PR to add this to the ola_trigger contrib folder (please):
https://github.com/OpenLightingProject/ola/tree/master/tools/ola_trigger/contrib

Although for that it would probably be good to put pulse in the middle, or possibly drop it, to match the GPIO module behaviour.

Have you considered guard bands like the OLA GPIO module has, so if you're running it on fader, there's not a point where the analogue aspect of the fader can cause it to flip between on and off continually.

**Comment by gobo-ws** [comment]
I tried to test OLAs GPIO plugin for a couple of years ago but I failed to get it working. I exported the GPIO pins and the olad user had permission to change the level on the pins but it never worked properly.
I must have done something wrong but I can give it another chance!

Yeah I can do a pull request and add it to the contrib folder.

I think we can drop the pulse function.

Thank you for the point of view! You're absolutely right, I can do something like the Hue config.
DMX value 0-114 relay off and 140-255 relay on.

**Comment by peternewman** [comment]
Yeah let us know on the mailing list, or pop into our IRC channel and someone can probably help you get the GPIO stuff working.

Thanks for the PR.

Interestingly our GPIO plugin doesn't have the guard band by default, I'll try and add that soon.
